package net.madicorp.autodoc.models;

// Generated 15 oct. 2014 10:48:29 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "Categorie", catalog = "autodocdb")
public class Categorie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6897313591665904367L;
	private int idCategorie;
	private String nomCategorie;
	private User user;
	private Set<Template> templates = new HashSet<Template>(0);
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<Gabarit> gabarits = new HashSet<Gabarit>(0);
	private Set<ObjectType> objectTypes = new HashSet<ObjectType>(0);

	public Categorie() {
	}

	public Categorie(int idCategorie) {
		this.idCategorie = idCategorie;
	}

	
	
	public Categorie(String nomCategorie) {
		super();
		this.nomCategorie = nomCategorie;
	}
	
	

	public Categorie(int idCategorie, String nomCategorie) {
		this.idCategorie = idCategorie;
		this.nomCategorie = nomCategorie;
	}
	
	

	public Categorie(String nomCategorie, User user) {
		super();
		this.nomCategorie = nomCategorie;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCategorie", unique = true, nullable = false)
	public int getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(int idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "nomCategorie", length = 45)
	public String getNomCategorie() {
		return this.nomCategorie;
	}

	public void setNomCategorie(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "User_idUser", nullable = true)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorie")
	public Set<Template> getTemplates() {
		return this.templates;
	}

	public void setTemplates(Set<Template> templates) {
		this.templates = templates;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorie")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorie")
	public Set<Gabarit> getGabarits() {
		return this.gabarits;
	}

	public void setGabarits(Set<Gabarit> gabarits) {
		this.gabarits = gabarits;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categorie")
	public Set<ObjectType> getObjectTypes() {
		return objectTypes;
	}

	public void setObjectTypes(Set<ObjectType> objectTypes) {
		this.objectTypes = objectTypes;
	}


	
	

}
