package net.madicorp.autodoc.models;

// Generated 15 oct. 2014 10:48:29 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "Document", catalog = "autodocdb")
public class Document implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5024675328973635255L;
	private int idDocument;
	private Categorie categorie;
	private Template template;
	private Gabarit gabarit;
	private String nomDocument;
	private Set<User> users = new HashSet<User>(0);

	public Document() {
	}
	
	

	public Document(Categorie categorie, Template template, Gabarit gabarit,
			String nomDocument) {
		super();
		this.categorie = categorie;
		this.template = template;
		this.gabarit = gabarit;
		this.nomDocument = nomDocument;
	}



	public Document(int idDocument, Categorie categorie, Template template,
			Gabarit gabarit) {
		this.idDocument = idDocument;
		this.categorie = categorie;
		this.template = template;
		this.gabarit = gabarit;
	}

	public Document(int idDocument, Categorie categorie, Template template,
			Gabarit gabarit, String nomDocument, Set<User> users) {
		this.idDocument = idDocument;
		this.categorie = categorie;
		this.template = template;
		this.gabarit = gabarit;
		this.nomDocument = nomDocument;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDocument", unique = true, nullable = false)
	public int getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(int idDocument) {
		this.idDocument = idDocument;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Categorie_idCategorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Template_idTemplate", nullable = true)
	public Template getTemplate() {
		return this.template;
	}

	public void setTemplate(Template template) {
		this.template = template;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Gabarit_idGabarit", nullable = true)
	public Gabarit getGabarit() {
		return this.gabarit;
	}

	public void setGabarit(Gabarit gabarit) {
		this.gabarit = gabarit;
	}

	@Column(name = "nomDocument", length = 65535)
	public String getNomDocument() {
		return this.nomDocument;
	}

	public void setNomDocument(String nomDocument) {
		this.nomDocument = nomDocument;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "User_Document", catalog = "autodocdb", joinColumns = { @JoinColumn(name = "Document_idDocument", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "User_idUser", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
