package net.madicorp.autodoc.models;

// Generated 15 oct. 2014 10:48:29 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Template generated by hbm2java
 */
@Entity
@Table(name = "Template", catalog = "autodocdb")
public class Template implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -54658703416492671L;
	private int idTemplate;
	private Categorie categorie;
	private String nomTemplate;
	private String type;
	private Set<Document> documents = new HashSet<Document>(0);

	public Template() {
	}

	public Template(int idTemplate, Categorie categorie) {
		this.idTemplate = idTemplate;
		this.categorie = categorie;
	}
	
	
	
	public Template(Categorie categorie, String nomTemplate, String type) {
		super();
		this.categorie = categorie;
		this.nomTemplate = nomTemplate;
		this.type = type;
	}

	public Template(int idTemplate, Categorie categorie, String nomTemplate,
			String type, Set<Document> documents) {
		this.idTemplate = idTemplate;
		this.categorie = categorie;
		this.nomTemplate = nomTemplate;
		this.type = type;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTemplate", unique = true, nullable = false)
	public int getIdTemplate() {
		return this.idTemplate;
	}

	public void setIdTemplate(int idTemplate) {
		this.idTemplate = idTemplate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Categorie_idCategorie", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "nomTemplate", length = 65535)
	public String getNomTemplate() {
		return this.nomTemplate;
	}

	public void setNomTemplate(String nomTemplate) {
		this.nomTemplate = nomTemplate;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "template")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}
	
	@Override
	public String toString() {
		return String.format("{%s/___/%s}", idTemplate, nomTemplate);
	}

}
